/*
 * Copyright (C) 2017 Nicolas
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package Ventanas;
import pedidos.*;
import java.awt.event.*;
import java.awt.*;

/**
 *
 * @author Nicolas
 */
public class VistaCotizar extends javax.swing.JInternalFrame {

    /**
     * Creates new form VistaCotizar
     */
    public VistaCotizar() {
        initComponents();
        Dimensiones.setVisible(false);
        CalibrePane.setVisible(false);
        ColorPane.setVisible(false);
        Cajon.setVisible(false);
    }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        SelectProduct = new javax.swing.JLabel();
        Producto = new javax.swing.JComboBox<>();
        Dimensiones = new javax.swing.JPanel();
        AltoLabel = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        Alto = new javax.swing.JTextPane();
        AnchoLabel = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        Ancho = new javax.swing.JTextPane();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        ColorPane = new javax.swing.JPanel();
        ColorLabel = new javax.swing.JLabel();
        Color = new javax.swing.JComboBox<>();
        Cajon = new javax.swing.JPanel();
        CantoLabel = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        Canto = new javax.swing.JTextPane();
        TubosLabel = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        Tubos = new javax.swing.JTextPane();
        LedsLabel = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        Leds = new javax.swing.JTextPane();
        ManoLabel = new javax.swing.JLabel();
        jScrollPane8 = new javax.swing.JScrollPane();
        Mano = new javax.swing.JTextPane();
        OtrosLabel = new javax.swing.JLabel();
        jScrollPane9 = new javax.swing.JScrollPane();
        Otros = new javax.swing.JTextPane();
        CalibrePane = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Calibre = new javax.swing.JTextPane();
        CalLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(720, 580));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(720, 570));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        jLabel1.setText("Cotizar un Producto");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 30, -1, -1));

        SelectProduct.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        SelectProduct.setText("Producto a cotizar: ");
        jPanel3.add(SelectProduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 100, -1, -1));

        Producto.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        Producto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione un producto", "Polietileno", "Acrilico", "Cajon" }));
        Producto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProductoActionPerformed(evt);
            }
        });
        jPanel3.add(Producto, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 100, -1, -1));

        Dimensiones.setBackground(new java.awt.Color(255, 255, 255));
        Dimensiones.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        AltoLabel.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        AltoLabel.setText("Alto:");
        Dimensiones.add(AltoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, -1, -1));

        jScrollPane2.setViewportView(Alto);

        Dimensiones.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 10, 180, -1));

        AnchoLabel.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        AnchoLabel.setText("Ancho:");
        Dimensiones.add(AnchoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 50, -1, -1));

        jScrollPane4.setViewportView(Ancho);

        Dimensiones.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 50, 180, -1));

        jLabel3.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel3.setText("cm");
        Dimensiones.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 10, -1, -1));

        jLabel4.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel4.setText("cm");
        Dimensiones.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 50, -1, -1));

        jPanel3.add(Dimensiones, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 160, 430, 80));

        ColorPane.setBackground(new java.awt.Color(255, 255, 255));
        ColorPane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ColorLabel.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        ColorLabel.setText("Color:");
        ColorPane.add(ColorLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, -1, -1));

        Color.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        Color.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione un color", "Blanco", "Cristal", "Otros" }));
        ColorPane.add(Color, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 10, 180, -1));

        jPanel3.add(ColorPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 280, 430, 50));

        Cajon.setBackground(new java.awt.Color(255, 255, 255));
        Cajon.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        CantoLabel.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        CantoLabel.setText("Canto:");
        Cajon.add(CantoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(129, 10, 50, -1));

        jScrollPane5.setViewportView(Canto);

        Cajon.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 10, 180, -1));

        TubosLabel.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        TubosLabel.setText("Tubos:");
        Cajon.add(TubosLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 50, -1, -1));

        jScrollPane6.setViewportView(Tubos);

        Cajon.add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 50, 180, -1));

        LedsLabel.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        LedsLabel.setText("Leds:");
        Cajon.add(LedsLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, -1, -1));

        jScrollPane7.setViewportView(Leds);

        Cajon.add(jScrollPane7, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 90, 180, -1));

        ManoLabel.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        ManoLabel.setText("Manofcatura:");
        Cajon.add(ManoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 130, -1, -1));

        jScrollPane8.setViewportView(Mano);

        Cajon.add(jScrollPane8, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 130, 180, -1));

        OtrosLabel.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        OtrosLabel.setText("Otros:");
        Cajon.add(OtrosLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 170, -1, -1));

        jScrollPane9.setViewportView(Otros);

        Cajon.add(jScrollPane9, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 170, 180, -1));

        jPanel3.add(Cajon, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 250, 430, 210));

        CalibrePane.setBackground(new java.awt.Color(255, 255, 255));
        CalibrePane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setViewportView(Calibre);

        CalibrePane.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 10, 180, -1));

        CalLabel.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        CalLabel.setText("Calibre:");
        CalibrePane.add(CalLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, -1, -1));

        jLabel2.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel2.setText("mm");
        CalibrePane.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 10, -1, -1));

        jPanel3.add(CalibrePane, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 240, 430, 40));

        jScrollPane3.setViewportView(jPanel3);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -10, 770, 570));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 749, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 560, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProductoActionPerformed
        // TODO add your handling code here:
        switch(Producto.getSelectedItem().toString())
        {
        case "Polietileno":
                Dimensiones.setVisible(true);
                CalibrePane.setVisible(true);
                ColorPane.setVisible(false);
                Cajon.setVisible(false);
                break;
            case "Acrilico":
                Dimensiones.setVisible(true);
                ColorPane.setVisible(true);
                CalibrePane.setVisible(true);
                Cajon.setVisible(false);
                break;
            case "Cajon":
                Dimensiones.setVisible(true);
                CalibrePane.setVisible(false);
                ColorPane.setVisible(false);
                Cajon.setVisible(true);
                break;
        }
    }//GEN-LAST:event_ProductoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextPane Alto;
    private javax.swing.JLabel AltoLabel;
    private javax.swing.JTextPane Ancho;
    private javax.swing.JLabel AnchoLabel;
    private javax.swing.JPanel Cajon;
    private javax.swing.JLabel CalLabel;
    private javax.swing.JTextPane Calibre;
    private javax.swing.JPanel CalibrePane;
    private javax.swing.JTextPane Canto;
    private javax.swing.JLabel CantoLabel;
    private javax.swing.JComboBox<String> Color;
    private javax.swing.JLabel ColorLabel;
    private javax.swing.JPanel ColorPane;
    private javax.swing.JPanel Dimensiones;
    private javax.swing.JTextPane Leds;
    private javax.swing.JLabel LedsLabel;
    private javax.swing.JTextPane Mano;
    private javax.swing.JLabel ManoLabel;
    private javax.swing.JTextPane Otros;
    private javax.swing.JLabel OtrosLabel;
    private javax.swing.JComboBox<String> Producto;
    private javax.swing.JLabel SelectProduct;
    private javax.swing.JTextPane Tubos;
    private javax.swing.JLabel TubosLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    // End of variables declaration//GEN-END:variables
}
