/*
 * Copyright (C) 2017 Nicolas
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package Ventanas;

import javax.swing.DefaultComboBoxModel;
import javax.swing.table.DefaultTableModel;
import pedidos.Empleado;
import pedidos.Factura;
import pedidos.Produccion;
import pedidos.Producto;

/**
 *
 * @author Nicolas
 */
public class VistaProduccion extends javax.swing.JInternalFrame {

    Produccion produccion;
    /**
     * Creates new form VistaProduccion
     */
    public VistaProduccion(Factura factura) {
        produccion = new Produccion(factura);
        initComponents();
        mostrar();
    }
    
    public void mostrar()
    {
        String prueba = produccion.getCliente().getNombres() + " " + produccion.getCliente().getApellidos();
        MostrarClienteP.setText(prueba);
        FechaIn.setText(produccion.getFechaInicial());
        DefaultComboBoxModel combo = new DefaultComboBoxModel();
        combo.addElement("Seleccione un Empleado");
        for(Empleado empl : new Empleado().obtenerOperarios())
        {
            combo.addElement(empl.getNombres() + " " + empl.getApellidos());
        }
        EmpleadoCombo.setModel(combo);
        
        DefaultTableModel table = new DefaultTableModel();
        String [] titulo = new String []{"Item", "Descripción"};
        table.setColumnIdentifiers(titulo);
        int i=0;
        for(Producto product: produccion.getProductos())
        {
            i++;
            table.addRow(new String[]{
                Integer.toString(i), product.detalles()
            });
        }
        Tabla.setModel(table);
        Tabla.getColumn("Item").setPreferredWidth(60);
        Tabla.getColumn("Descripción").setPreferredWidth(402);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        ClienteProduc = new javax.swing.JLabel();
        MostrarClienteP = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        EmpleadoCombo = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        FechaIn = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        Tabla = new javax.swing.JTable();
        FechaFin = new com.toedter.calendar.JDateChooser();

        jDesktopPane1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        jLabel1.setText("Orden de Producción");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 20, -1, -1));

        ClienteProduc.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        ClienteProduc.setText("Cliente:");
        jPanel1.add(ClienteProduc, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, -1, -1));

        MostrarClienteP.setEditable(false);
        MostrarClienteP.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jPanel1.add(MostrarClienteP, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, 260, 30));

        jLabel2.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel2.setText("Asignar Operario:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        EmpleadoCombo.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        EmpleadoCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione un operario" }));
        jPanel1.add(EmpleadoCombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 120, 260, -1));

        jLabel3.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel3.setText("Fecha Terminado:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 120, -1, -1));

        jLabel4.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel4.setText("Fecha Inicio:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 80, -1, -1));

        FechaIn.setEditable(false);
        FechaIn.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jPanel1.add(FechaIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 80, 150, -1));

        jLabel5.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel5.setText("Productos");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 180, -1, -1));

        Tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        Tabla.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jScrollPane2.setViewportView(Tabla);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 210, 470, 230));
        jPanel1.add(FechaFin, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 120, 150, 30));

        jDesktopPane1.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 710, 560));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 704, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 558, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ClienteProduc;
    private javax.swing.JComboBox<String> EmpleadoCombo;
    private com.toedter.calendar.JDateChooser FechaFin;
    private javax.swing.JTextField FechaIn;
    private javax.swing.JTextField MostrarClienteP;
    private javax.swing.JTable Tabla;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
