/*
 * Copyright (C) 2017 Nicolas
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package Ventanas;

import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import pedidos.Empleado;
import pedidos.Factura;
import pedidos.GeneradorPDF;
import pedidos.Produccion;
import pedidos.Producto;
import pedidos.Pedido;

/**
 *
 * @author Nicolas
 */
public class VistaProduccion extends javax.swing.JInternalFrame {

    Produccion produccion;
    Pedido pedido;
    /**
     * Creates new form VistaProduccion
     */
    public VistaProduccion(Factura factura, Pedido pedido) {
        this.pedido = pedido;
        produccion = new Produccion(factura);
        initComponents();
        mostrar();
    }
    
    public void mostrar()
    {
        String prueba = produccion.getCliente().getNombres() + " " + produccion.getCliente().getApellidos();
        MostrarClienteP.setText(prueba);
        FechaIn.setText(produccion.getFechaInicial());
        DefaultComboBoxModel combo = new DefaultComboBoxModel();
        combo.addElement("Seleccione un Empleado");
        for(Empleado empl : new Empleado().obtenerOperarios())
        {
            combo.addElement(empl.getNombres() + " " + empl.getApellidos());
        }
        EmpleadoCombo.setModel(combo);
        
        DefaultTableModel table = new DefaultTableModel();
        String [] titulo = new String []{"Item", "Descripción"};
        table.setColumnIdentifiers(titulo);
        int i=0;
        for(Producto product: produccion.getProductos())
        {
            i++;
            table.addRow(new String[]{
                Integer.toString(i), product.detalles()
            });
        }
        Tabla.setModel(table);
        Tabla.getColumn("Item").setPreferredWidth(60);
        Tabla.getColumn("Descripción").setPreferredWidth(402);
    }
    
//    public Empleado setOperario(String nombre)
//    {
//        
//    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        Fondo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        ClienteProduc = new javax.swing.JLabel();
        MostrarClienteP = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        EmpleadoCombo = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        FechaIn = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        Tabla = new javax.swing.JTable();
        FechaFin = new com.toedter.calendar.JDateChooser();
        Imprimir = new javax.swing.JButton();
        Terminar = new javax.swing.JButton();

        jDesktopPane1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Fondo.setBackground(new java.awt.Color(255, 255, 255));
        Fondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        jLabel1.setText("Orden de Producción");
        Fondo.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 20, -1, -1));

        ClienteProduc.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        ClienteProduc.setText("Cliente:");
        Fondo.add(ClienteProduc, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, -1, -1));

        MostrarClienteP.setEditable(false);
        MostrarClienteP.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        Fondo.add(MostrarClienteP, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, 260, 30));

        jLabel2.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel2.setText("Asignar Operario:");
        Fondo.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        EmpleadoCombo.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        EmpleadoCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione un operario" }));
        Fondo.add(EmpleadoCombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 120, 260, -1));

        jLabel3.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel3.setText("Fecha Terminado:");
        Fondo.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 120, -1, -1));

        jLabel4.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel4.setText("Fecha Inicio:");
        Fondo.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 80, -1, -1));

        FechaIn.setEditable(false);
        FechaIn.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        Fondo.add(FechaIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 80, 150, -1));

        jLabel5.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel5.setText("Productos");
        Fondo.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 180, -1, -1));

        Tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        Tabla.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jScrollPane2.setViewportView(Tabla);

        Fondo.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 210, 470, 230));
        Fondo.add(FechaFin, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 120, 150, 30));

        Imprimir.setBackground(new java.awt.Color(204, 51, 0));
        Imprimir.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        Imprimir.setForeground(new java.awt.Color(255, 255, 255));
        Imprimir.setText("Imprimir Orden");
        Imprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ImprimirActionPerformed(evt);
            }
        });
        Fondo.add(Imprimir, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 470, -1, -1));

        Terminar.setBackground(new java.awt.Color(204, 51, 0));
        Terminar.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        Terminar.setForeground(new java.awt.Color(255, 255, 255));
        Terminar.setText("Terminar");
        Terminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TerminarActionPerformed(evt);
            }
        });
        Fondo.add(Terminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 470, -1, -1));

        jDesktopPane1.add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 710, 560));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 704, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 558, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ImprimirActionPerformed
        // TODO add your handling code here:
        Validador validar = new Validador();
        
        Date fechaNacimientoCliente = FechaFin.getDate();
        if(fechaNacimientoCliente == null){
            JOptionPane.showMessageDialog(this, "Existe Algun Campo Vacío", "Error!", JOptionPane.ERROR_MESSAGE);    
        }
        SimpleDateFormat format1 = new SimpleDateFormat("yyyy-MM-dd");
        String formatted = format1.format(fechaNacimientoCliente);
        produccion.setFechaInicial(FechaIn.getText());
        produccion.setFechaEntrega(formatted);
        validar.ValidarVacio(EmpleadoCombo.getSelectedItem().toString(), this);
        List<Empleado> lista = new Empleado().obtenerOperarios();
        produccion.setEmpleado(lista.get(EmpleadoCombo.getSelectedIndex()-1));
        produccion.setIdEmpleado(produccion.getEmpleado().getID());
        GeneradorPDF pdf = new GeneradorPDF();
        pdf.PdfProduccion(produccion);
        produccion.crearProduccion();
        
    }//GEN-LAST:event_ImprimirActionPerformed

    private void TerminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TerminarActionPerformed
        // TODO add your handling code here:
        pedido.setIdProduccion(produccion.getIdProduccion());
        pedido.GuardarIdProduccion();
        GestorPedidos pedidos = new GestorPedidos();
        Interfaz.Escritorio.removeAll();
        pedidos.setVisible(true);
        Interfaz.Escritorio.add(pedidos);
    }//GEN-LAST:event_TerminarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ClienteProduc;
    private javax.swing.JComboBox<String> EmpleadoCombo;
    private com.toedter.calendar.JDateChooser FechaFin;
    private javax.swing.JTextField FechaIn;
    private javax.swing.JPanel Fondo;
    private javax.swing.JButton Imprimir;
    private javax.swing.JTextField MostrarClienteP;
    private javax.swing.JTable Tabla;
    private javax.swing.JButton Terminar;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
