/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;

import java.text.SimpleDateFormat;
import java.util.Date;
import pedidos.Cliente;

/**
 *
 * @author Nicolas
 */
public class VistaCliente extends javax.swing.JInternalFrame {

    /**
     * Creates new form GestosPedidos
     */
    public VistaCliente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        JLNombre = new javax.swing.JLabel();
        JLApellido = new javax.swing.JLabel();
        JLTelefono = new javax.swing.JLabel();
        JLEmail = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtApellidos = new javax.swing.JTextField();
        txtTelefono = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        JLGenero = new javax.swing.JLabel();
        txtGenero = new javax.swing.JComboBox<>();
        JLFechaNacimiento = new javax.swing.JLabel();
        JDFechaNacimiento = new com.toedter.calendar.JDateChooser();
        btnGuardar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        JLDireccion = new javax.swing.JLabel();
        txtDireccion = new javax.swing.JTextField();
        JLIdentificacion = new javax.swing.JLabel();
        txtIdentificacion = new javax.swing.JTextField();

        setFocusable(false);
        setPreferredSize(new java.awt.Dimension(720, 580));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        jLabel5.setText("Registrar un Cliente");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 30, 310, -1));

        JLNombre.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        JLNombre.setText("Nombres:");
        getContentPane().add(JLNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 90, -1, -1));

        JLApellido.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        JLApellido.setText("Apellidos:");
        getContentPane().add(JLApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 140, -1, -1));

        JLTelefono.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        JLTelefono.setText("Telefono:");
        getContentPane().add(JLTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 240, -1, -1));

        JLEmail.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        JLEmail.setText("E-mail:");
        getContentPane().add(JLEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 290, -1, -1));

        txtNombre.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });
        getContentPane().add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 90, 229, -1));

        txtApellidos.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        getContentPane().add(txtApellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 140, 230, -1));

        txtTelefono.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        getContentPane().add(txtTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 240, 230, -1));

        txtEmail.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        getContentPane().add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 290, 232, -1));

        JLGenero.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        JLGenero.setText("Genero :");
        getContentPane().add(JLGenero, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 340, -1, -1));

        txtGenero.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        txtGenero.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione un Genero", "Masculino", "Femenino" }));
        txtGenero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGeneroActionPerformed(evt);
            }
        });
        getContentPane().add(txtGenero, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 340, 230, -1));

        JLFechaNacimiento.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        JLFechaNacimiento.setText("Fecha Nacimiento:");
        getContentPane().add(JLFechaNacimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 390, -1, -1));
        getContentPane().add(JDFechaNacimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 390, 230, 30));

        btnGuardar.setBackground(new java.awt.Color(204, 51, 0));
        btnGuardar.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        btnGuardar.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        getContentPane().add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 500, 130, -1));

        btnLimpiar.setBackground(new java.awt.Color(204, 51, 0));
        btnLimpiar.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        btnLimpiar.setForeground(new java.awt.Color(255, 255, 255));
        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });
        getContentPane().add(btnLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 500, 130, -1));

        JLDireccion.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        JLDireccion.setText("Direccion:");
        getContentPane().add(JLDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 440, -1, -1));

        txtDireccion.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        getContentPane().add(txtDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 440, 232, -1));

        JLIdentificacion.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        JLIdentificacion.setText("Identificacion:");
        getContentPane().add(JLIdentificacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 190, -1, -1));

        txtIdentificacion.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        getContentPane().add(txtIdentificacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 190, 230, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void txtGeneroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGeneroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGeneroActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
        String nombreCliente = txtNombre.getText();
        String apellidoCliente = txtApellidos.getText();
        String Identificacion = txtIdentificacion.getText();
        String correoCliente = txtEmail.getText();
        String generoCliente = txtGenero.getSelectedItem().toString();
        String direccionCliente = txtDireccion.getText();
        String telefonoCliente = txtTelefono.getText();
        Date fechaNacimientoCliente = JDFechaNacimiento.getDate();
        SimpleDateFormat format1 = new SimpleDateFormat("yyyy-MM-dd");
        String formatted = format1.format(fechaNacimientoCliente);
        Cliente cliente = new Cliente( nombreCliente , apellidoCliente, Identificacion , formatted , generoCliente , direccionCliente, telefonoCliente, correoCliente);
        cliente.crearUsuario();
        
        
        System.out.println(formatted);
    }//GEN-LAST:event_btnGuardarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser JDFechaNacimiento;
    private javax.swing.JLabel JLApellido;
    private javax.swing.JLabel JLDireccion;
    private javax.swing.JLabel JLEmail;
    private javax.swing.JLabel JLFechaNacimiento;
    private javax.swing.JLabel JLGenero;
    private javax.swing.JLabel JLIdentificacion;
    private javax.swing.JLabel JLNombre;
    private javax.swing.JLabel JLTelefono;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField txtApellidos;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JComboBox<String> txtGenero;
    private javax.swing.JTextField txtIdentificacion;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
